"""Perplexity and Delta-PPL, per the paper's Equations 3 and 4.

    PPL(x)    = exp( -(1/L) * sum_i log P(x_i | x_<i) )
    PPL(x, d) = exp( -(1/L) * sum_i log P(x_i | x_<i, d) )
    Delta-PPL = PPL(x) - PPL(x, d)          (Equation 3)

A positive Delta-PPL means the document *lowered* perplexity, i.e. raised the
model's confidence in the scored sequence.

Which tokens are scored -- documented assumption
-----------------------------------------------
Equation 4, read literally, sums over the *query* tokens ``x``. That contradicts
the paper's prose in three places: the abstract ("perplexity-based labels **of
rationales**"), section 2.1 ("we measure perplexity differences in the
**rationales generated by the base LLM**"), and Figure 2, whose "Lower
Perplexity" node is tagged **Rationale**. This module therefore scores the
**rationale**, conditioned on a prompt that does or does not carry the document;
``filter_training.ppl_target: query`` selects the literal reading instead. See
docs/rag2_reproduction.md section 5.4.

The *same* rationale string -- the one generated without retrieval -- is scored
in both terms, so Delta-PPL isolates the document's effect on one fixed
sequence rather than confounding it with a different generation's length and
content (``filter_training.ppl_rationale``).
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Any, Dict, Optional, Sequence

from ..llm.base import LLM, ScoredSequence
from ..prompts import DEFAULT_PROMPTS, PromptSet
from ..schema import Evidence, Question


def perplexity_from_scores(scored: ScoredSequence) -> float:
    """exp( -mean token log-probability ). Equation 4."""
    if scored.num_tokens == 0:
        return float("inf")
    return math.exp(-scored.sum_logprob / scored.num_tokens)


@dataclass
class PerplexityPair:
    """The two perplexities of Equation 3, plus their difference."""

    ppl_without: float
    ppl_with: float
    num_tokens: int = 0

    @property
    def delta(self) -> float:
        """Delta-PPL = PPL(x) - PPL(x, d); positive = document raised confidence."""
        return self.ppl_without - self.ppl_with

    def to_dict(self) -> Dict[str, Any]:
        return {
            "ppl_without": self.ppl_without,
            "ppl_with": self.ppl_with,
            "delta_ppl": self.delta,
            "num_tokens": self.num_tokens,
        }


def compute_perplexity_pair(
    llm: LLM,
    question: Question,
    rationale: str,
    evidence: Evidence | str,
    prompts: Optional[PromptSet] = None,
    target: str = "rationale",
) -> PerplexityPair:
    """Score one (question, snippet) pair.

    Both terms condition on the same prompt shape the pipeline actually uses --
    the closed-book prompt without the document, the with-evidence prompt with
    it -- so Delta-PPL measures exactly the intervention the filter must predict.
    """
    prompts = prompts or DEFAULT_PROMPTS
    prompt_without = prompts.render_answer_prompt(question, [])
    prompt_with = prompts.render_answer_prompt(question, [evidence])

    if target == "query":
        # The literal reading of Equation 4: score the query itself.
        scored_without = llm.score("", prompts.render_question(question))
        scored_with = llm.score(
            prompts.render_evidence_block([evidence]), prompts.render_question(question)
        )
    elif target == "rationale":
        scored_without = llm.score(prompt_without, rationale)
        scored_with = llm.score(prompt_with, rationale)
    else:
        raise ValueError(f"unknown ppl target {target!r}; expected 'rationale' or 'query'")

    return PerplexityPair(
        ppl_without=perplexity_from_scores(scored_without),
        ppl_with=perplexity_from_scores(scored_with),
        num_tokens=scored_without.num_tokens,
    )


def percentile(values: Sequence[float], q: float) -> float:
    """Linear-interpolation percentile, stdlib only (numpy-compatible)."""
    finite = sorted(v for v in values if v == v and abs(v) != float("inf"))
    if not finite:
        return float("nan")
    if len(finite) == 1:
        return finite[0]
    position = (q / 100.0) * (len(finite) - 1)
    lower = math.floor(position)
    upper = math.ceil(position)
    if lower == upper:
        return finite[int(position)]
    weight = position - lower
    return finite[lower] * (1 - weight) + finite[upper] * weight


def top_percent_threshold(deltas: Sequence[float], top_percent: float = 25.0) -> float:
    """tau such that the top ``top_percent`` of Delta-PPL values satisfy ``delta >= tau``.

    The paper fixes ``top_percent`` at 25 across all experiments (section 3.2).
    """
    if not 0 < top_percent <= 100:
        raise ValueError(f"top_percent must be in (0, 100], got {top_percent}")
    return percentile(deltas, 100.0 - top_percent)
