#!/usr/bin/env python3
"""Generate the Q01-Q07 PubMed query families from the versioned config.

Queries are GENERATED, never hand-edited, so the MeSH scope and controlled
vocabulary cannot drift apart from the queries that use them.

Every family AND-s an Alzheimer's anchor block. No family retrieves on a
supporting concept alone - that is what keeps this an Alzheimer's corpus rather
than a dementia corpus (spec section 32).
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[3]
CONFIG = ROOT / "alzheimer_corpus" / "config"
OUTDIR = ROOT / "alzheimer_corpus" / "queries" / "pubmed"

FAMILIES = {
    "Q01_alzheimer_core":         ("Alzheimer core", None),
    "Q02_alzheimer_clinical":     ("Alzheimer clinical / staging", "clinical_stages"),
    "Q03_alzheimer_biomarkers":   ("Alzheimer biomarkers", "biomarkers"),
    "Q04_alzheimer_amyloid_tau":  ("Alzheimer amyloid / tau", "pathology"),
    "Q05_alzheimer_diagnosis":    ("Alzheimer diagnosis", "diagnosis"),
    "Q06_alzheimer_treatment":    ("Alzheimer treatment", "treatment"),
    "Q07_alzheimer_differential": ("Alzheimer differential diagnosis", None),
}


def _or(parts: list[str]) -> str:
    return "(" + " OR ".join(parts) + ")"


def anchor_block(mesh: dict, vocab: dict) -> str:
    """The Alzheimer's anchor. AND-ed into every family without exception."""
    parts = [f'"{t["descriptor"]}"[Mesh]' for t in mesh["tiers"]["primary"]["terms"]]
    for term in vocab["groups"]["disease_terminology"]["terms"]:
        parts.append(f'"{term}"[tiab]')
    return _or(parts)


def concept_block(vocab: dict, group: str) -> str:
    return _or([f'"{t}"[tiab]' for t in vocab["groups"][group]["terms"]])


def differential_block(mesh: dict) -> str:
    return _or([f'"{t["descriptor"]}"[Mesh]' for t in mesh["tiers"]["differential"]["terms"]]
               + ['"differential diagnosis"[tiab]', '"Diagnosis, Differential"[Mesh]'])


def build(mesh: dict, vocab: dict, qid: str) -> str:
    anchor = anchor_block(mesh, vocab)
    label, group = FAMILIES[qid]
    if qid == "Q01_alzheimer_core":
        body = None
    elif qid == "Q07_alzheimer_differential":
        body = differential_block(mesh)
    else:
        body = concept_block(vocab, group)
    header = (
        f"# {qid} - {label}\n"
        f"# GENERATED by alzheimer_corpus/scripts/retrieval/build_queries.py - do not hand-edit.\n"
        f"# mesh_terms.yaml v{mesh['version']} | controlled_vocabulary.yaml v{vocab['version']}\n"
        f"# The Alzheimer's anchor block is AND-ed into every family: no family may\n"
        f"# retrieve on a supporting concept alone.\n"
        f"# Record hit count and run date after a count-only (dry-run) execution.\n"
        f"# Hits: ____  Date: ____\n\n"
    )
    q = anchor if body is None else f"{anchor}\nAND\n{body}"
    return header + q + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default=str(OUTDIR))
    ap.add_argument("--check", action="store_true",
                    help="verify on-disk files match the config; do not write")
    args = ap.parse_args(argv)

    mesh = yaml.safe_load((CONFIG / "mesh_terms.yaml").read_text())
    vocab = yaml.safe_load((CONFIG / "controlled_vocabulary.yaml").read_text())
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    drift = []
    for qid in FAMILIES:
        text = build(mesh, vocab, qid)
        path = outdir / f"{qid}.txt"
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                drift.append(qid)
        else:
            path.write_text(text, encoding="utf-8", newline="\n")
            print(f"wrote {path.name}  ({len(text)} chars)")
    if args.check:
        if drift:
            print("DRIFT:", ", ".join(drift)); return 1
        print("OK - all query files match the config")
    return 0


if __name__ == "__main__":
    sys.exit(main())
